// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DemoAndroidAPI.Repositories.Models;

public partial class Book
{
    public Book(string name, string description, int? price, bool? isSold)
    {
        Name = name;
        Description = description;
        Price = price;
        IsSold = isSold;
    }

    public Book(int id, string name, string description, int? price, bool? isSold)
    {
        Id = id;
        Name = name;
        Description = description;
        Price = price;
        IsSold = isSold;
    }

    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? Price { get; set; }

    public bool? IsSold { get; set; }
}